name: optox
channels:
  - conda-forge
dependencies:
  - python=3.6
  - cmake=3.12
  - matplotlib=3.1
  - numpy
  - pip
  - setuptools
  - six
  - wheel
  - pip
  - cudatoolkit=11.0
  - gcc_linux-64=8.5.0
  - gxx_linux-64=8.5.0
  - pip:
    - -r requirements.txt
